spring:
  application:
    name: user-cenetr
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/user_center_database
    username: root
    password: 1430
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


server:
  port: 8080
  servlet:
    context-path: /api

